name: CI

on:
  push:
    branches:
      - main  # Menjalankan tes saat push ke branch 'main'
  pull_request:
    branches:
      - main  # Menjalankan tes saat ada pull request ke branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Versi Node.js yang digunakan (ubah jika perlu)

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
